[features]
seeds = false
skip-lint = false
[programs.localnet]
kaheclub = "AByC8vWQntfskq889DFGq6nc9EXVGi725X3em2Nnfjis"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kaz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
